version: '3'

include:
  - ./src/web_server_client/docker-compose.yaml

name: sagittarius
services:
  compiler:
    container_name: sagittarius-compiler
    build:
      context: ./src/compiler/
      dockerfile: Dockerfile
    ports:
      - ${COMPILER_PORT}:8080
    environment:
      GRAFANA_URL: ${GRAFANA_API_URL}
      DEPLOY_URL: ${DEPLOYER_URL}

  deployer:
    container_name: sagittarius-deployer
    build:
      context: ./src/deployer
      dockerfile: Dockerfile
    ports:
      - ${DEPLOYER_PORT}:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
      AZURE_GROUP_NAME: ${AZURE_GROUP_NAME}
      AZURE_APP_PLAN: ${AZURE_APP_PLAN}
      AZURE_FILE_SHARE_CONNECTION_STRING: ${AZURE_FILE_SHARE_CONNECTION_STRING}
      AZURE_FILE_SHARE_NAME: ${AZURE_FILE_SHARE_NAME}
      AZURE_USERNAME: ${AZURE_USERNAME}
      AZURE_PASSWORD: ${AZURE_PASSWORD}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      APP_URL_CONFIG: ${APP_URL_CONFIG}
      APP_DOCKER_REGISTRY_SERVER_URL: ${APP_DOCKER_REGISTRY_SERVER_URL}
      APP_DOCKER_REGISTRY_SERVER_USERNAME: ${APP_DOCKER_REGISTRY_SERVER_USERNAME}
      APP_DOCKER_REGISTRY_SERVER_PASSWORD: ${APP_DOCKER_REGISTRY_SERVER_PASSWORD}
      APP_WEBSITES_ENABLE_APP_SERVICE_STORAGE: ${APP_WEBSITES_ENABLE_APP_SERVICE_STORAGE}
      APP_DATASOURCE_URL: ${APP_DATASOURCE_URL}
      APP_GF_SECURITY_ADMIN_PASSWORD: ${APP_GF_SECURITY_ADMIN_PASSWORD}
      APP_GF_SECURITY_ADMIN_USER: ${APP_GF_SECURITY_ADMIN_USER}
      APP_GEOCODING_KEY: ${APP_GEOCODING_KEY}
      APP_SECRET_KEY: ${APP_SECRET_KEY}
      DOCKER_REG_PASSWORD: ${DOCKER_REG_PASSWORD}

  grafana:
    container_name: sagittarius-grafana
    build:
      context: ./src/grafana_dashboard
    ports:
      - ${GRAFANA_API_PORT}:9000
    restart: always
    extra_hosts:
      - "localhost:host-gateway"


  orion:
    image: telefonicaiot/fiware-orion
    container_name: fiware-orion
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -logLevel INFO -dbURI mongodb://mongo
    #                              ^^^^^^^^^^^^^^^^
    #                                         ↳ this can be any connection string:
    #                                             - docker: mongodb://mongo
    #                                             - local or docker: mongodb://localhost (if port in docker is exposed)
    #                                             - any other host: cloud storage or another laptop mongodb://<any public url or IP address>
    #

  mongo:
    image: mongo:6.0
    restart: always
    container_name: mongo
    ports:
      - 27017:27017

  fiware-admin:
    container_name: fiware-admin
    build:
      context: .
      dockerfile: fiware_admin.Dockerfile
      #            ^^^^^^^^^^^^^^^^^^^^^^^
      #                          ↳ this can be any docker file, you can keep it here or move it somewhere else
    depends_on:
      - orion
