// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppType } from "./AppType";
import type { PageLayout } from "./PageLayout";

export interface App { type: AppType, layout: PageLayout, }