// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Credentials } from "./Credentials";
import type { DeploymentType } from "./DeploymentType";
import type { URI } from "./URI";

export interface DeploymentEnv { name: string, uri: URI, port: number, type: DeploymentType | null, credentials: Credentials | null, }