// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentEnv } from "./DeploymentEnv";

export interface Deployment { envs: Array<DeploymentEnv>, }