// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyType = "String" | "Integer" | "Double" | "Number" | "Boolean" | "Timestamp" | "Capacity" | "Length";