// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";
import type { Version } from "./Version";

export interface Preamble { name: string, version: Version, scope: Scope, }