// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Scope = "Service" | "Industry" | "Manifacturing" | "Education" | "Healthcare" | "SocialPrograms" | "Government" | "Energy" | "Water" | "Environment" | "Transportation" | "Communication" | "PublicSafety" | "UrbanPlanning";