// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";
import type { SensorFormat } from "./SensorFormat";
import type { SensorType } from "./SensorType";
import type { URI } from "./URI";

export interface Sensor { name: string, type: SensorType, provider: Provider, uri: URI, format: SensorFormat, }