// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Data } from "./Data";
import type { Deployment } from "./Deployment";
import type { FileInfo } from "./FileInfo";
import type { Preamble } from "./Preamble";
import type { Service } from "./Service";

export interface SSD { info: FileInfo, preamble: Preamble, data: Data, service: Service, deployment: Deployment, }