// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Protocol } from "./Protocol";

export interface URI { protocol: Protocol, host: string, path: string | null, }