// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedType } from "./NamedType";
import type { VisualizationType } from "./VisualizationType";

export interface Visualization { name: string, type: VisualizationType, data: Array<NamedType>, }